### ISSUE TITLE
App Open Error version  3.5.6.6x64

### ISSUE THREAD

**Issue by seletok** [paul1956/CareLink#23]
Dear Paul,

I have the error below when open the app:
 at CareLink.CareLinkUserDataList.ContainsKey(String key) in C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\Records\UserDataRecords\CareLinkUserDataList.vb:line 164
   at CareLink.LoginForm1.LoginForm1_Load(Object sender, EventArgs e) in C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\Forms\LoginForm1.vb:line 54
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

With Ok and Cancel option. Ok do nothing, app crashes.

Please verify.

Regards,
Koteles Ferenc

**Comment by seletok** [comment]
Now see the method to solve. Clear the carelink.csv file from Documents folder.
Sorry for issue report.

**Comment by paul1956** [comment]
@seletok I will post a fix this weekend but until then you found the solution.

**Comment by paul1956** [comment]
Fixed in CareLink3.5.6.7x64
